services:
  dedicated-server-save-sync:
    env_file:
      - path: ${SAVE_SYNC_LOCAL_ENV_FILE:-.env.local}
        required: true
    ports:
      - 127.0.0.1:${SAVE_SYNC_LOCAL_PORT:-18080}:8080
    volumes:
      - save_sync_local_data:/data/save-sync
      - ./config/games/${SAVE_SYNC_GAME_KEY:-palworld}.json:/app/game.json:ro

  backup-supervisor:
    env_file:
      - path: ${SAVE_SYNC_LOCAL_ENV_FILE:-.env.local}
        required: true
    volumes:
      - save_sync_local_data:/data/save-sync

networks:
  traefik_proxy:
    name: ${SAVE_SYNC_LOCAL_NETWORK:-save-sync-local}
    external: false

volumes:
  save_sync_local_data:
    name: ${SAVE_SYNC_LOCAL_VOLUME:-save-sync-local-data}
